#选择要执行的yml文件
spring:
  profiles:
    active: dev

#打印出执行的sql
#logging:
#  level:
#    com.lqtest.druid_mybatis.lqtest.dao : debug

#规定端口
server:
  port: 8081
  servlet:
    context-path: /sptest

#mybatis位置和包配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lqstudy.druid_mybatis.lqtest.entity


threadPool:
  corePoolSize: 10
  maxPoolSize: 20
  queueCapacity: 25