
# 服务端口
server:
  port : 8086
  # 注册中心url
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8082/eureka
  # 注册中心名字
spring:
  application:
    name : service-config
  # 配置存储地址(git)
  cloud:
    config:
      server:
        git:
          uri : https://github.com/jacklq/myProject.git
  # 存储文件夹
          search-paths : 4-1-myconfig

  # git主分支
      label : master